### ISSUE TITLE
Dead Link Of Requires.io 

### ISSUE THREAD

**Issue by IAmAMissingColon** [openwisp/django-netjsongraph#100]
The link of requires.io mentioned in README section is faulty/wrong  and needs to be updated

**Comment by atb00ker** [comment]
Needs to be updated to https://requires.io/github/openwisp/django-netjsongraph/requirements/?branch=master

**Comment by IAmAMissingColon** [comment]
Closing as it's done ! :smile:

**Comment by atb00ker** [comment]
@IAmAMissingColon Please reopen it. The related pull request is not merged. 
When the pull request is merged, you'll see that it closes automatically ( If you've used `Closes #<issue>` )

**Comment by IAmAMissingColon** [comment]
Oh sorry, didn't know about that
