### ISSUE TITLE
Can't update node JSON

### ISSUE THREAD

**Issue by willzhang05** [openwisp/django-netjsongraph#87]
I was playing around with django-netjsongraph, and I'm having issues with updating the JSON for individual nodes within a NetworkGraph topology. For instance, if I wanted to update the label of a node in a NetworkGraph topology and sent the updated NetworkGraph in a POST request to the API, the API never updates the node's JSON.

I looked through the code, and in [base/topology.py](https://github.com/netjson/django-netjsongraph/blob/master/django_netjsongraph/base/topology.py#L207) on lines 207-209, it says that if the node exists, it will just skip to the next iteration. Is there a reason for not updating node JSON, or is it just something that hasn't been implemented?

Thanks!

**Comment by nemesisdesign** [comment]
@willzhang05 the latter, sorry for the late response
