### ISSUE TITLE
[dependencies] Add support for django 2.1 and  2.2

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-netjsongraph#98]
Add support for django 2.1 and  2.2.

**Comment by Weirdo914** [comment]
I think this is solved in https://github.com/openwisp/django-netjsongraph/commit/c2a6ed5cffa5726fcd69adc86fe43b7d554755f4

**Comment by atb00ker** [comment]
It seems that @Weirdo914 is correct.
@nemesisdesign I don't have access to this repository, can you please cross-check and close this? 
Thanks. :smile:
